name: Build ZMK firmware

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main
    with:
      shield_matrix: |
        [
          "corne_left",
          "corne_right"
        ]
      board_matrix: |
        [
          "nice_nano_v2"
        ]
